// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: health.sql

package db

import (
	"context"
)

const healthCheck = `-- name: HealthCheck :exec
SELECT 1
`

func (q *Queries) HealthCheck(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, healthCheck)
	return err
}
